### ISSUE TITLE
Add bubble sort algorithm

### ISSUE THREAD

**Issue by Prashant0664** [Prashant0664/hacktoberfest#15]

**Comment by lazyMonk1010** [comment]
hey Prashant!! i want to add bubble sort algorithm , please assign me this issue.

**Comment by Prashant0664** [comment]
Assigned to @lazyMonk1010

**Comment by lazyMonk1010** [comment]
you forgot to actually assign me the issue.

**Comment by lazyMonk1010** [comment]
i have completed the work please check it
