### ISSUE TITLE
Add Quick Sort Algorithm

### ISSUE THREAD

**Issue by Prashant0664** [Prashant0664/hacktoberfest#16]

**Comment by ghost** [comment]
@Prashant0664  plz assign this issue to me

**Comment by Prashant0664** [comment]
Ok

**Comment by Durgeshsejekar** [comment]
I want to work on this issue so please can you assign me this issue

**Comment by kittoteja** [comment]
please can you assign me this issue

**Comment by ghost** [comment]
@Prashant0664  i have submitted the code plz check
