### ISSUE TITLE
Add Selection Sort

### ISSUE THREAD

**Issue by Prashant0664** [Prashant0664/hacktoberfest#17]
Please Star⭐️ the repo or follow @Prashant0664 if you like this repository.

**Comment by ghost** [comment]
@Prashant0664 plz assign this issue to me

**Comment by Durgeshsejekar** [comment]
@Prashant0664 i want to work on this issue plz can you assign me.

**Comment by ghost** [comment]
@Prashant0664 , Sir I have submitted the code for selection sort plz check
