### ISSUE TITLE
Add Insertion Sort Algorithm

### ISSUE THREAD

**Issue by Prashant0664** [Prashant0664/hacktoberfest#18]
Please Star⭐️ the repo or follow @Prashant0664 if you like this repository.(Optional)

**Comment by Durgeshsejekar** [comment]
I want to work on this issue so please you can assign me.

**Comment by kittoteja** [comment]
Please assign it to me

**Comment by nexuspy** [comment]
I want to work On this!

**Comment by Prashant0664** [comment]
Write solution in different languages otherwise there will be first come first serve rule for pull request

**Comment by Durgeshsejekar** [comment]
I have added the insertion sort algo so please check it and merge the PR

**Comment by Vaiofficial** [comment]
After reviewing this repository, I'm eager to contribute to this particular issue. Could you please assign this issue to me?

**Comment by Prashant0664** [comment]
> After reviewing this repository, I'm eager to contribute to this particular issue. Could you please assign this issue to me?

This issue has already been assigned, you can add some other solution or algo if you like.
