### ISSUE TITLE
Add Merge Sort Algo.

### ISSUE THREAD

**Issue by Prashant0664** [Prashant0664/hacktoberfest#20]
Please Star⭐️ the repo or follow @Prashant0664 if you like this repository.(Optional)

**Comment by kittoteja** [comment]
Please assign it to me

**Comment by nexuspy** [comment]
Can I Work on This ?

**Comment by Shantanusharnagat** [comment]
@Prashant0664 I would like to work on this. Could you assign it to me

**Comment by Prashant0664** [comment]
Write solution in different languages otherwise there will be first come first serve rule for pull request

**Comment by asryan11** [comment]
Is this issue still open? If it is open, can you assign it to me?
