### ISSUE TITLE
Add Merge Without extra space(link in desc)

### ISSUE THREAD

**Issue by Prashant0664** [Prashant0664/hacktoberfest#21]
https://practice.geeksforgeeks.org/problems/merge-two-sorted-arrays-1587115620/1?page=1&difficulty[]=2&category[]=Sorting&sortBy=submissions

**Comment by Durgeshsejekar** [comment]
Hey prashant, I want to work on this issue can you assign me this issue

**Comment by Prashant0664** [comment]
ok

**Comment by kittoteja** [comment]
want to work on this issue can you assign me this issue
