### ISSUE TITLE
Add solution to Median of subarray

### ISSUE THREAD

**Issue by Prashant0664** [Prashant0664/hacktoberfest#22]
https://practice.geeksforgeeks.org/problems/median-of-the-subarrays--170647/1?page=1&difficulty[]=2&category[]=Sorting&sortBy=submissions

**Comment by m-jalmby** [comment]
Could I work on this one?

**Comment by kittoteja** [comment]
Please assign it to me

**Comment by Prashant0664** [comment]
ok
