### ISSUE TITLE
Add Kadane Algorithm 

### ISSUE THREAD

**Issue by Prashant0664** [Prashant0664/hacktoberfest#3]
Link : https://practice.geeksforgeeks.org/problems/kadanes-algorithm-1587115620/1?page=1&company[]=Microsoft&sortBy=submissions

**Comment by Raj-sharma01** [comment]
hello, can you please assign me this issue

**Comment by Prashant0664** [comment]
Ok, Assigned to @Raj-sharma01. Please star this repo if you liked.

**Comment by ghost** [comment]
@Prashant0664 , Hello sir, can u plz assign this issue to me?

**Comment by Prashant0664** [comment]
Already assigned, you can add another problem. @TheHackracer7 
and don't forgot to star and follow

**Comment by ghost** [comment]
@Prashant0664 ,Sir I am new to this, i just wanted to know , only one person can be can be assigned per issue?

**Comment by Prashant0664** [comment]
> Sir I am new to this, i just wanted to know , only one person can be can be assigned per issue?

No, it is not necessary, but suppose if I assign two people the same problem, and both people try to add his code, then only one code can be added, other person efforts will waste even if he requested first. So we usually assign one issue per person. If there is a demand for something like design then we can assign an issue to many persons and will select only a good one and on the basis of who solved the issue first. It will be mentioned in the issue itself.
If someone has not solved the issue on time then we can assign that issue to someone else

**Comment by ghost** [comment]
@Prashant0664 , ok sir I get it now, so has @Raj-sharma01 submitted successfully?

**Comment by Prashant0664** [comment]
> @Prashant0664 , ok sir I get it now, so has @Raj-sharma01 submitted successfully?

Not yet, will assign to someone else if not submitted within 24 hrs of creating an issue.(don't forgot to star repo and follow @Prashant0664), I will added new issues soon.

**Comment by ghost** [comment]
ok sir thankyou

**Comment by ghost** [comment]
@Prashant0664 sir if @Raj-sharma01 dosent submits on time then plz assign me
