### ISSUE TITLE
Add N-Queens problem solution in C++

### ISSUE THREAD

**Issue by blindaks** [Prashant0664/hacktoberfest#31]
The n-queens puzzle is the problem of placing n queens on an n x n chessboard such that no two queens attack each other.

Given an integer n, return all distinct solutions to the n-queens puzzle. You may return the answer in any order.

Each solution contains a distinct board configuration of the n-queens' placement, where 'Q' and '.' both indicate a queen and an empty space, respectively.

 Example 1:

![image](https://github.com/Prashant0664/hacktoberfest/assets/128223364/b24c769d-2646-466a-9fa3-cebd756bc5d6)

Input: n = 4
Output: [[".Q..","...Q","Q...","..Q."],["..Q.","Q...","...Q",".Q.."]]
Explanation: There exist two distinct solutions to the 4-queens puzzle as shown above

Example 2:

Input: n = 1
Output: [["Q"]]
 
Constraints:
1 <= n <= 9

**Comment by blindaks** [comment]
Please assign this issue to me under Hacktoberfest.

**Comment by Prashant0664** [comment]
ok
