### ISSUE TITLE
Add paranthesis checker algorithm in any language

### ISSUE THREAD

**Issue by Prashant0664** [Prashant0664/hacktoberfest#4]
Link : https://practice.geeksforgeeks.org/problems/parenthesis-checker2744/1?page=1&company[]=Microsoft&sortBy=submissions

**Comment by aman4uas** [comment]
Hey @Prashant0664  !! Can you please assign this to me?

**Comment by Prashant0664** [comment]
Assigned to @aman4uas . Please Star this repo if you liked.

**Comment by aman4uas** [comment]
@Prashant0664 Yeah sure thanks !!
