### ISSUE TITLE
Add sol to median of two sorted array

### ISSUE THREAD

**Issue by Prashant0664** [Prashant0664/hacktoberfest#47]
https://leetcode.com/problems/median-of-two-sorted-arrays/
Dont forgot to star and follow @Prashant0664 if you like our repo!!

**Comment by arjungupta01** [comment]
Hey can you assign me this problem , i am willing to solve it .

**Comment by arjungupta01** [comment]
@Prashant0664 bro why have u not assigned it ??😥😥

**Comment by Prashant0664** [comment]
Already merged
