### ISSUE TITLE
Solve substring-with-concatenation-of-all-words

### ISSUE THREAD

**Issue by Prashant0664** [Prashant0664/hacktoberfest#49]
https://leetcode.com/problems/substring-with-concatenation-of-all-words/
Dont forgot to star and follow @Prashant0664 if you like our repo!!

**Comment by AdityaDhavale** [comment]
I would love to work on this issue . Please assign me

**Comment by devvrat011** [comment]
pls assign this to me. I am a competitive programmer. I am specialist on codeforces and 4 star on codechef.
Thank you
