### ISSUE TITLE
Add 0-1 Knapsack in any language

### ISSUE THREAD

**Issue by Prashant0664** [Prashant0664/hacktoberfest#5]
https://practice.geeksforgeeks.org/problems/0-1-knapsack-problem0945/1?page=1&company[]=Microsoft&sortBy=submissions

**Comment by Subhashini014** [comment]
hello Prashanth0664 could you please assign me this problem.

**Comment by Prashant0664** [comment]
Assigned to @Subhashini014 . Please Star the Repo

**Comment by Subhashini014** [comment]
Thank you.

**Comment by Subhashini014** [comment]
hello Prashanth0664 it is not showing star option in my github could you help me to star your repositry.

**Comment by Prashant0664** [comment]
Click on the Code -> then you will see the Star option near fork option at top right of repo

**Comment by Subhashini014** [comment]
Thank you.

**Comment by Subhashini014** [comment]
From Intelliji idea I am trying to push the code it is showing that git push is falied for me. could you please provide me any resources to push the request.

**Comment by Subhashini014** [comment]
Actually I am newbie to Hacktoberfest please help me how to do push the request in terminal.

**Comment by Prashant0664** [comment]
> Actually I am newbie to Hacktoberfest please help me how to do push the request in terminal.

Resources:
https://hacktoberfest.com/participation/
After successfully forking and cloning into local machine -> 
Try `git pull`(there maybe changes in original repo after you clone the repo)
-> git add .
-> git commit -m "namecommit"
-> git push -u origin main
-> Go to your forked repository
-> Click on create pull request
-> Done

**Comment by priyesh0453** [comment]
Follow this short clip if you are having trouble via Git Bash. It's all the same. Nevertheless, the GUI might make it easier: [VS Code GitHub Guide](https://www.youtube.com/watch?v=h-LgFUiK_UM). You can reference from here, too, as to where exactly you are finding issues in push.

**Comment by Subhashini014** [comment]
I need to add my code in try.text or should I create new .java file in java folder.

**Comment by Subhashini014** [comment]
Did my code is uploaded to you in java folder could you please check it.

**Comment by Prashant0664** [comment]
> Did my code is uploaded to you in java folder could you please check it.

No,
Check if you have created pull request from your repo after uploading.
After successfully creating pull request, you will see your pull request in `Pull Requests` option at top of this repo.
