### ISSUE TITLE
Add a simple web development project

### ISSUE THREAD

**Issue by Prashant0664** [Prashant0664/hacktoberfest#54]
Guidelines:
Add files into a folder with your project name,
then add that folder into MERN folder of Repo;
This issue is open to everyone

**Comment by bishwobista** [comment]
Hey, what type of project do you want? just boilerplate or full project? Which stack to use?

**Comment by vd89** [comment]
Hey @Prashant0664  

Will like to take this work and add some boiler plate of a mern project for the same

**Comment by parag477** [comment]
i would like to work on this issue. Please assign me

**Comment by AdityaDhavale** [comment]
I would love to work on this issue . Please assign it to me

**Comment by Prashant0664** [comment]
This issue is open to everyone means you all can create pull request, there will be no assignment just follow protocol of adding files 
Files should be added in MERN or Web development folder with format
MERN/web development -> your project folder name-> files
Not 
❌MERN/WEB DEVELOPMENT-> files(index.js, .css, html...)❌

And don't forgot to star repo and follow @Prashant0664 if you like(optional)

**Comment by bishwobista** [comment]
@Prashant0664 , boilerplate code or full project?

**Comment by Prashant0664** [comment]
Anything, your choice @bishwobista

**Comment by Git-Akshat01** [comment]
Hi! @Prashant0664 i had added a project please check and merge the PR.

**Comment by Samaresh-Das** [comment]
I will contribute

**Comment by Devasahoo123** [comment]
please assign to me i have good hand on web development, I am ready to contribute

**Comment by AdityaDhavale** [comment]
Hi @Prashant0664 I added a project file in MERN folder of repo , please check and merge my PR.

**Comment by Git-Akshat01** [comment]
Guys this repo is excluded from hacktoberfest 2023. So please take the required action @Prashant0664

**Comment by AniketP04** [comment]
I'm willing to work on this issue and collaborate with the maintainers. Please let me know how I can proceed.
