### ISSUE TITLE
Add POTD of Leetcode

### ISSUE THREAD

**Issue by Prashant0664** [Prashant0664/hacktoberfest#7]
POTD: Problem of the Day Solution

**Comment by darshil25** [comment]
hey @Prashant0664 assign this to me

**Comment by Prashant0664** [comment]
Assigned to @darshil25

**Comment by darshil25** [comment]
hey @Prashant0664 i have done the task kindly check it

**Comment by darshil25** [comment]
It is showing that you rejected my pull request
May i know the reason?
